---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.1
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[syslog-ng_test::default]
    driver_config:
      require_chef_omnibus: <%= ENV.fetch('CHEF_OMNIBUS_VERSION', true) %>
