Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  Max: 100

Layout/SpaceBeforeFirstArg:
  Enabled: false

Style/FileName:
  Exclude:
    - test/integration/default/serverspec/syslog-ng_daemon_spec.rb
